# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NursingHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=512)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('provider_type', models.CharField(blank=True, max_length=25)),
                ('grade_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('grade_care', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('web', models.CharField(blank=True, max_length=1024)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Geographic location')),
                ('search_index', djorm_pgfulltext.fields.VectorField()),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'nursing home',
                'verbose_name_plural': 'nursing homes',
            },
        ),
        migrations.CreateModel(
            name='SupervisionAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('fds_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fds_url', models.CharField(blank=True, max_length=255)),
                ('report', models.FileField(blank=True, upload_to=b'')),
                ('nursing_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correctiv_nursinghomes.NursingHome')),
                ('report_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correctiv_nursinghomes.SupervisionAuthority')),
            ],
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='supervision_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correctiv_nursinghomes.SupervisionAuthority'),
        ),
    ]
