# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_nursinghomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursinghome',
            name='care_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='care_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='care_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='care_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='red_flag_decubitus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='red_flag_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='red_flag_incontinence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='red_flag_medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='red_flag_pain',
            field=models.BooleanField(default=False),
        ),
    ]
