# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_nursinghomes', '0002_auto_20160523_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionauthority',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supervisionauthority',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supervisionauthority',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supervisionauthority',
            name='report_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='supervisionauthority',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='supervisionauthority',
            name='fds_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='supervisionreport',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
