# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geogermany', '0003_auto_20160525_1639'),
        ('correctiv_nursinghomes', '0003_auto_20160525_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursinghome',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geogermany.District'),
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geogermany.State'),
        ),
    ]
