# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_nursinghomes', '0005_auto_20160525_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisionauthority',
            name='report_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='supervisionauthority',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
