# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geogermany', '0005_auto_20160526_1451'),
        ('correctiv_nursinghomes', '0006_auto_20160525_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionauthority',
            name='borough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geogermany.Borough'),
        ),
    ]
