# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_nursinghomes', '0008_supervisionreport_report_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisionreport',
            options={'ordering': ('-date',), 'verbose_name': 'Supervision Report', 'verbose_name_plural': 'Supervision Reports'},
        ),
    ]
