# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_nursinghomes', '0009_auto_20160530_2123'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nursinghome',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='nursinghome',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nursinghome',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('freigemeinn\xfctzig', 'charitable'), ('privat', 'private'), ('\xf6ffentlich', 'public'), ('nicht zu ermitteln', 'unknown')], max_length=25),
        ),
    ]
