# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_nursinghomes', '0010_auto_20160622_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursinghome',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nursinghome',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursinghomes_in_district', to='geogermany.District'),
        ),
        migrations.AlterField(
            model_name='nursinghome',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursinghomes_in_state', to='geogermany.State'),
        ),
        migrations.AlterField(
            model_name='supervisionauthority',
            name='borough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisionauthorities_in_borough', to='geogermany.Borough'),
        ),
        migrations.AlterField(
            model_name='supervisionauthority',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisionauthorities_in_district', to='geogermany.District'),
        ),
        migrations.AlterField(
            model_name='supervisionauthority',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisionauthorities_in_state', to='geogermany.State'),
        ),
    ]
